services:
  web:
    image: nginx:1.25.5-alpine3.19
    container_name: web
    volumes:
      - ./web/livin:/livin:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
  postgres:
    image: postgres:16.3-alpine3.19
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./app/resources/start.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - 5432:5432
